output = "models"
wipe = true
no-tests = false

[auto-columns]
created = "createdAt"
updated = "updatedAt"

[psql]
dbname = "checkinboard"
host = "localhost"
port = 5432
user = "michzuerch"
pass = "lx0lc33a"
schema = "public"
sslmode = "disable"
blacklist = ["migrations"]

[mysql]
dbname = "checkinboard"
host = "localhost"
port = 3306
user = "michzuerch"
pass = "lx0lc33a"
sslmode = "false"

[sqlite3]
dbname = "/home/michzuerch/Source/CheckInBoardServer/checkinboard-testing.db"
blacklist = ["migrations"]

[mssql]
dbname = "checkinboard"
host = "localhost"
port = 1433
user = "michzuerch"
pass = "lx0lc33a"
sslmode = "disable"
schema = "notdbo"
