version: '3.3'

services:
  database:
    image: 'postgres:14-alpine'
    # user: "${UID}:${GID}"
    ports:
      - 5432:5432
    env_file:
      - .env # The name of your environment file (the one at the repository root)
    volumes:
      - checkinboard-db:/var/lib/postgresql/data/
        #  checkinboard-server:
        #image: 'checkinboard-server'
        #ports:
        #- ${HTTP_PORT}:${HTTP_PORT}
        #env_file:
        #- .env

volumes:
  checkinboard-db:
