version: '3'
services:
  database:
    image: 'postgres:latest'
    user: "${UID}:${GID}"
    ports:
      - 5432:5432
    env_file:
      - .env # The name of your environment file (the one at the repository root)
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
        #  checkinboard-server:
        #image: 'checkinboard-server'
        #ports:
        #- ${HTTP_PORT}:${HTTP_PORT}
        #env_file:
        #- .env
