version: '3.3'

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'checkinboard'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'michzuerch'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'lx0lc33a'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'lx0lc33a'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - checkinboard-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080

# Names our volume
volumes:
  checkinboard-db:
