version: '3.3'

services:
  database:
    image: 'postgres:14-alpine'
    container_name: 'postgres'
    # user: "${UID}:${GID}"
    ports:
      - 5432:5432
    env_file:
      - .env # The name of your environment file (the one at the repository root)
    volumes:
      - checkinboard-db:/var/lib/postgresql/data/
        #  checkinboard-server:
        #image: 'checkinboard-server'
        #ports:
        #- ${HTTP_PORT}:${HTTP_PORT}
        #env_file:
        #- .env

  backend:
    image: 'checkinboard-server'
    container_name: 'checkinboard-server'
    ports:
      - 8080:8080
    env_file:
      - .env
volumes:
  checkinboard-db:
